[package]
name = "libcras"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
libc = "*"
sys_util = { path = "../../../../../platform/crosvm/sys_util" }
data_model = { path = "../../../../../platform/crosvm/data_model" }
cras_common = { path = "../cras_common" }
